apiVersion: v1
kind: Pod
metadata:
  name: growi
spec:
  restartPolicy: Always
  volumes:
    - name: growi_data
      hostPath:
        path:  #growiのデータ保存先
    - name: mongo_config
      hostPath:
        path:  #mongodbのconfig保存先
    - name: mongo_db
      hostPath:
        path:  #mongodbのdb保存先
    - name: es_data
      hostPath:
        path:  #elasticsearchのデータ保存先
    - name: es_conf
      hostPath:
        path:  #elasticsearchの設定ファイル

  containers:
    - name: mongo-container
      image: docker.io/mongo
      imagePullPolicy: Never
      volumeMounts:
        - name: mongo_config
          mountPath: /data/configdb
        - name: mongo_db
          mountPath: /data/db

    - name: elasticsearch-container
      image: localhost/elasticsearch
      imagePullPolicy: Never
      env:
        - name: bootstrap.memory_lock
          value: true
        - name: ES_JAVA_OPTS
          value: -Xms1792m -Xmx1792m
      volumeMounts:
        - name: es_data
          mountPath: /usr/share/elasticsearch/data
        - name: es_conf
          mountPath: /usr/share/elasticsearch/config/elasticsearch.yml

    - name: growi-container
      image: weseek/growi:4.2.11
      imagePullPolicy: Never
      workingDir: /opt/growi
      env:
        - name: PORT
          value: 3000
        - name: NODE_ENV
          value: production
        - name: MONGO_URI
          value: mongodb://127.0.0.1:27017/growi
        - name: ELASTICSEARCH_URI
          value: http://127.0.0.1:9200/growi
        - name: PASSWORD_SEED
          value: #change me #openssl rand -base64 128 | head -1 でシードを生成してセット
        - name: FILE_UPLOAD
          value: local
        - name: MATHJAX
          value: 1
      ports:
        - containerPort: 3000
          hostPort: 3000
          protocol: TCP
      volumeMounts:
        - name: growi_data
          mountPath: /data
